using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using HoldemPlayerContract;

namespace GMachine
{
    internal class PreFlopCalculator : StageCalculator
    {
        Dictionary<string, Dictionary<int, double>> pocketProbs;

        //public override ActionType GetAction(GameState gameState, out int amount)
        //{
        //    amount = gameState.CallAmount;
        //    return ActionType.Call;
        //}

        /*
                // !!! this should adjust action for pairs, suited and unsuited depending on num opponents and position
                // or even better put logic into EstProbWinningShowdown and adjust probability depending on cards, num opponents and position
                public override ActionType GetAction(GameState gameState, out int amount )
                {
                    amount = 0;
                    ActionType yourAction = ActionType.Fold;

                    PlayerProfile myPlayerProfile = gameState.Players[gameState.MyPlayerId];
                    int callAmount = gameState.CallAmount;
                    int minRaise = gameState.MinRaise;

                    PocketCards pocketCards = gameState.MyCards;

                    ERankType highRank = pocketCards.HighCard.Rank;
                    ERankType lowRank = pocketCards.LowCard.Rank;

                    if (pocketCards.IsPair)
                    {
                        if (highRank >= ERankType.RankEight)
                        {
                            yourAction = ActionType.Raise; 
                            amount = minRaise;
                        }
                        else if (highRank >= ERankType.RankFive)
                        {
                            yourAction = ActionType.Call;
                            amount = callAmount;
                        }
                    }
                    else
                    {
                        if (highRank >= ERankType.RankKing && lowRank >= ERankType.RankJack)
                        {
                            if(pocketCards.IsSuited)
                            {        
                                yourAction = ActionType.Raise;
                                amount = minRaise;
                            }
                            else
                            {
                                yourAction = ActionType.Call;
                                amount = callAmount;
                            }
                        }
                        else if (pocketCards.IsSuited && pocketCards.GapBetweenHighAndLow == 1)
                        {
                            yourAction = ActionType.Call;
                            amount = callAmount;
                        }
                    }

                    return yourAction;
                }
        */

        /*
                public override double EstProbWinningShowdown(GameState gameState)
                {
                    int numUnseen = gameState.UnseenCards.Count;

                    Dictionary<string, double> opponentHands = new Dictionary<string, double>();

                    Card[] opponentHoleCards = new Card[2];
                    int[] results = new int[3];

                    for (int i = 0; i < numUnseen; i++)
                    {
                        opponentHoleCards[0] = gameState.UnseenCards[i];

                        for (int j = i + 1; j < numUnseen; j++)
                        {
                            opponentHoleCards[1] = gameState.UnseenCards[j];
                            PocketCards opponentCards = new PocketCards(opponentHoleCards[0], opponentHoleCards[1]);

                            double probBeatingOpponentHand = ProbHand1BeatsHand2(gameState.MyCards.RankDescription(), opponentCards.RankDescription()); // Look up prob of my hand beating opponent hand

                            string opponentHandString = opponentHoleCards[0].ValueStr() + opponentHoleCards[1].ValueStr();
                            opponentHands.Add(opponentHandString, probBeatingOpponentHand);
                        }
                    }

                    // !!! This bit is common to preflop/flop/turn/river - should not be duplicated
                    double estimate = 1;

                    foreach(PlayerProfile p in gameState.ActiveOpponents())
                    {
                        double probBeatingThisOpponent = 0;

                        foreach(KeyValuePair<string,double> kvp in opponentHands)
                        {
                            probBeatingThisOpponent += kvp.Value * p.PointsForPossibleHands.PointsForHand(kvp.Key);
                        }

                        probBeatingThisOpponent /=  p.PointsForPossibleHands.TotalPoints;

                        estimate *= probBeatingThisOpponent;
                    }

                    return estimate;
                }

                private double ProbHand1BeatsHand2(string sHand1, string sHand2)
                {
                    if(sHand1 == sHand2)
                    {
                        return 0.5;
                    }

                    // !!! do stuff here
                    return 0.5;
                }
        */
        public PreFlopCalculator()
        {
            pocketProbs = new Dictionary<string, Dictionary<int, double>>();

            pocketProbs.Add("AA", new Dictionary<int, double>());
            pocketProbs.Add("AKs", new Dictionary<int, double>());
            pocketProbs.Add("AKo", new Dictionary<int, double>());
            pocketProbs.Add("AQs", new Dictionary<int, double>());
            pocketProbs.Add("AQo", new Dictionary<int, double>());
            pocketProbs.Add("AJs", new Dictionary<int, double>());
            pocketProbs.Add("AJo", new Dictionary<int, double>());
            pocketProbs.Add("ATs", new Dictionary<int, double>());
            pocketProbs.Add("ATo", new Dictionary<int, double>());
            pocketProbs.Add("A9s", new Dictionary<int, double>());
            pocketProbs.Add("A9o", new Dictionary<int, double>());
            pocketProbs.Add("A8s", new Dictionary<int, double>());
            pocketProbs.Add("A8o", new Dictionary<int, double>());
            pocketProbs.Add("A7s", new Dictionary<int, double>());
            pocketProbs.Add("A7o", new Dictionary<int, double>());
            pocketProbs.Add("A6s", new Dictionary<int, double>());
            pocketProbs.Add("A6o", new Dictionary<int, double>());
            pocketProbs.Add("A5s", new Dictionary<int, double>());
            pocketProbs.Add("A5o", new Dictionary<int, double>());
            pocketProbs.Add("A4s", new Dictionary<int, double>());
            pocketProbs.Add("A4o", new Dictionary<int, double>());
            pocketProbs.Add("A3s", new Dictionary<int, double>());
            pocketProbs.Add("A3o", new Dictionary<int, double>());
            pocketProbs.Add("A2s", new Dictionary<int, double>());
            pocketProbs.Add("A2o", new Dictionary<int, double>());
            pocketProbs.Add("KK", new Dictionary<int, double>());
            pocketProbs.Add("KQs", new Dictionary<int, double>());
            pocketProbs.Add("KQo", new Dictionary<int, double>());
            pocketProbs.Add("KJs", new Dictionary<int, double>());
            pocketProbs.Add("KJo", new Dictionary<int, double>());
            pocketProbs.Add("KTs", new Dictionary<int, double>());
            pocketProbs.Add("KTo", new Dictionary<int, double>());
            pocketProbs.Add("K9s", new Dictionary<int, double>());
            pocketProbs.Add("K9o", new Dictionary<int, double>());
            pocketProbs.Add("K8s", new Dictionary<int, double>());
            pocketProbs.Add("K8o", new Dictionary<int, double>());
            pocketProbs.Add("K7s", new Dictionary<int, double>());
            pocketProbs.Add("K7o", new Dictionary<int, double>());
            pocketProbs.Add("K6s", new Dictionary<int, double>());
            pocketProbs.Add("K6o", new Dictionary<int, double>());
            pocketProbs.Add("K5s", new Dictionary<int, double>());
            pocketProbs.Add("K5o", new Dictionary<int, double>());
            pocketProbs.Add("K4s", new Dictionary<int, double>());
            pocketProbs.Add("K4o", new Dictionary<int, double>());
            pocketProbs.Add("K3s", new Dictionary<int, double>());
            pocketProbs.Add("K3o", new Dictionary<int, double>());
            pocketProbs.Add("K2s", new Dictionary<int, double>());
            pocketProbs.Add("K2o", new Dictionary<int, double>());
            pocketProbs.Add("QQ", new Dictionary<int, double>());
            pocketProbs.Add("QJs", new Dictionary<int, double>());
            pocketProbs.Add("QJo", new Dictionary<int, double>());
            pocketProbs.Add("QTs", new Dictionary<int, double>());
            pocketProbs.Add("QTo", new Dictionary<int, double>());
            pocketProbs.Add("Q9s", new Dictionary<int, double>());
            pocketProbs.Add("Q9o", new Dictionary<int, double>());
            pocketProbs.Add("Q8s", new Dictionary<int, double>());
            pocketProbs.Add("Q8o", new Dictionary<int, double>());
            pocketProbs.Add("Q7s", new Dictionary<int, double>());
            pocketProbs.Add("Q7o", new Dictionary<int, double>());
            pocketProbs.Add("Q6s", new Dictionary<int, double>());
            pocketProbs.Add("Q6o", new Dictionary<int, double>());
            pocketProbs.Add("Q5s", new Dictionary<int, double>());
            pocketProbs.Add("Q5o", new Dictionary<int, double>());
            pocketProbs.Add("Q4s", new Dictionary<int, double>());
            pocketProbs.Add("Q4o", new Dictionary<int, double>());
            pocketProbs.Add("Q3s", new Dictionary<int, double>());
            pocketProbs.Add("Q3o", new Dictionary<int, double>());
            pocketProbs.Add("Q2s", new Dictionary<int, double>());
            pocketProbs.Add("Q2o", new Dictionary<int, double>());
            pocketProbs.Add("JJ", new Dictionary<int, double>());
            pocketProbs.Add("JTs", new Dictionary<int, double>());
            pocketProbs.Add("JTo", new Dictionary<int, double>());
            pocketProbs.Add("J9s", new Dictionary<int, double>());
            pocketProbs.Add("J9o", new Dictionary<int, double>());
            pocketProbs.Add("J8s", new Dictionary<int, double>());
            pocketProbs.Add("J8o", new Dictionary<int, double>());
            pocketProbs.Add("J7s", new Dictionary<int, double>());
            pocketProbs.Add("J7o", new Dictionary<int, double>());
            pocketProbs.Add("J6s", new Dictionary<int, double>());
            pocketProbs.Add("J6o", new Dictionary<int, double>());
            pocketProbs.Add("J5s", new Dictionary<int, double>());
            pocketProbs.Add("J5o", new Dictionary<int, double>());
            pocketProbs.Add("J4s", new Dictionary<int, double>());
            pocketProbs.Add("J4o", new Dictionary<int, double>());
            pocketProbs.Add("J3s", new Dictionary<int, double>());
            pocketProbs.Add("J3o", new Dictionary<int, double>());
            pocketProbs.Add("J2s", new Dictionary<int, double>());
            pocketProbs.Add("J2o", new Dictionary<int, double>());
            pocketProbs.Add("TT", new Dictionary<int, double>());
            pocketProbs.Add("T9s", new Dictionary<int, double>());
            pocketProbs.Add("T9o", new Dictionary<int, double>());
            pocketProbs.Add("T8s", new Dictionary<int, double>());
            pocketProbs.Add("T8o", new Dictionary<int, double>());
            pocketProbs.Add("T7s", new Dictionary<int, double>());
            pocketProbs.Add("T7o", new Dictionary<int, double>());
            pocketProbs.Add("T6s", new Dictionary<int, double>());
            pocketProbs.Add("T6o", new Dictionary<int, double>());
            pocketProbs.Add("T5s", new Dictionary<int, double>());
            pocketProbs.Add("T5o", new Dictionary<int, double>());
            pocketProbs.Add("T4s", new Dictionary<int, double>());
            pocketProbs.Add("T4o", new Dictionary<int, double>());
            pocketProbs.Add("T3s", new Dictionary<int, double>());
            pocketProbs.Add("T3o", new Dictionary<int, double>());
            pocketProbs.Add("T2s", new Dictionary<int, double>());
            pocketProbs.Add("T2o", new Dictionary<int, double>());
            pocketProbs.Add("99", new Dictionary<int, double>());
            pocketProbs.Add("98s", new Dictionary<int, double>());
            pocketProbs.Add("98o", new Dictionary<int, double>());
            pocketProbs.Add("97s", new Dictionary<int, double>());
            pocketProbs.Add("97o", new Dictionary<int, double>());
            pocketProbs.Add("96s", new Dictionary<int, double>());
            pocketProbs.Add("96o", new Dictionary<int, double>());
            pocketProbs.Add("95s", new Dictionary<int, double>());
            pocketProbs.Add("95o", new Dictionary<int, double>());
            pocketProbs.Add("94s", new Dictionary<int, double>());
            pocketProbs.Add("94o", new Dictionary<int, double>());
            pocketProbs.Add("93s", new Dictionary<int, double>());
            pocketProbs.Add("93o", new Dictionary<int, double>());
            pocketProbs.Add("92s", new Dictionary<int, double>());
            pocketProbs.Add("92o", new Dictionary<int, double>());
            pocketProbs.Add("88", new Dictionary<int, double>());
            pocketProbs.Add("87s", new Dictionary<int, double>());
            pocketProbs.Add("87o", new Dictionary<int, double>());
            pocketProbs.Add("86s", new Dictionary<int, double>());
            pocketProbs.Add("86o", new Dictionary<int, double>());
            pocketProbs.Add("85s", new Dictionary<int, double>());
            pocketProbs.Add("85o", new Dictionary<int, double>());
            pocketProbs.Add("84s", new Dictionary<int, double>());
            pocketProbs.Add("84o", new Dictionary<int, double>());
            pocketProbs.Add("83s", new Dictionary<int, double>());
            pocketProbs.Add("83o", new Dictionary<int, double>());
            pocketProbs.Add("82s", new Dictionary<int, double>());
            pocketProbs.Add("82o", new Dictionary<int, double>());
            pocketProbs.Add("77", new Dictionary<int, double>());
            pocketProbs.Add("76s", new Dictionary<int, double>());
            pocketProbs.Add("76o", new Dictionary<int, double>());
            pocketProbs.Add("75s", new Dictionary<int, double>());
            pocketProbs.Add("75o", new Dictionary<int, double>());
            pocketProbs.Add("74s", new Dictionary<int, double>());
            pocketProbs.Add("74o", new Dictionary<int, double>());
            pocketProbs.Add("73s", new Dictionary<int, double>());
            pocketProbs.Add("73o", new Dictionary<int, double>());
            pocketProbs.Add("72s", new Dictionary<int, double>());
            pocketProbs.Add("72o", new Dictionary<int, double>());
            pocketProbs.Add("66", new Dictionary<int, double>());
            pocketProbs.Add("65s", new Dictionary<int, double>());
            pocketProbs.Add("65o", new Dictionary<int, double>());
            pocketProbs.Add("64s", new Dictionary<int, double>());
            pocketProbs.Add("64o", new Dictionary<int, double>());
            pocketProbs.Add("63s", new Dictionary<int, double>());
            pocketProbs.Add("63o", new Dictionary<int, double>());
            pocketProbs.Add("62s", new Dictionary<int, double>());
            pocketProbs.Add("62o", new Dictionary<int, double>());
            pocketProbs.Add("55", new Dictionary<int, double>());
            pocketProbs.Add("54s", new Dictionary<int, double>());
            pocketProbs.Add("54o", new Dictionary<int, double>());
            pocketProbs.Add("53s", new Dictionary<int, double>());
            pocketProbs.Add("53o", new Dictionary<int, double>());
            pocketProbs.Add("52s", new Dictionary<int, double>());
            pocketProbs.Add("52o", new Dictionary<int, double>());
            pocketProbs.Add("44", new Dictionary<int, double>());
            pocketProbs.Add("43s", new Dictionary<int, double>());
            pocketProbs.Add("43o", new Dictionary<int, double>());
            pocketProbs.Add("42s", new Dictionary<int, double>());
            pocketProbs.Add("42o", new Dictionary<int, double>());
            pocketProbs.Add("33", new Dictionary<int, double>());
            pocketProbs.Add("32s", new Dictionary<int, double>());
            pocketProbs.Add("32o", new Dictionary<int, double>());
            pocketProbs.Add("22", new Dictionary<int, double>());

            pocketProbs["AA"].Add(2,0.85); 
            pocketProbs["AKs"].Add(2,0.67); 
            pocketProbs["AKo"].Add(2,0.65); 
            pocketProbs["AQs"].Add(2,0.66); 
            pocketProbs["AQo"].Add(2,0.65); 
            pocketProbs["AJs"].Add(2,0.65); 
            pocketProbs["AJo"].Add(2,0.64); 
            pocketProbs["ATs"].Add(2,0.65); 
            pocketProbs["ATo"].Add(2,0.63); 
            pocketProbs["A9s"].Add(2,0.63); 
            pocketProbs["A9o"].Add(2,0.61); 
            pocketProbs["A8s"].Add(2,0.62); 
            pocketProbs["A8o"].Add(2,0.60); 
            pocketProbs["A7s"].Add(2,0.61); 
            pocketProbs["A7o"].Add(2,0.59); 
            pocketProbs["A6s"].Add(2,0.60); 
            pocketProbs["A6o"].Add(2,0.58); 
            pocketProbs["A5s"].Add(2,0.60); 
            pocketProbs["A5o"].Add(2,0.58); 
            pocketProbs["A4s"].Add(2,0.59); 
            pocketProbs["A4o"].Add(2,0.56); 
            pocketProbs["A3s"].Add(2,0.58); 
            pocketProbs["A3o"].Add(2,0.56); 
            pocketProbs["A2s"].Add(2,0.57); 
            pocketProbs["A2o"].Add(2,0.55); 
            pocketProbs["KK"].Add(2,0.82); 
            pocketProbs["KQs"].Add(2,0.63); 
            pocketProbs["KQo"].Add(2,0.61); 
            pocketProbs["KJs"].Add(2,0.63); 
            pocketProbs["KJo"].Add(2,0.61); 
            pocketProbs["KTs"].Add(2,0.62); 
            pocketProbs["KTo"].Add(2,0.60); 
            pocketProbs["K9s"].Add(2,0.60); 
            pocketProbs["K9o"].Add(2,0.58); 
            pocketProbs["K8s"].Add(2,0.59); 
            pocketProbs["K8o"].Add(2,0.56); 
            pocketProbs["K7s"].Add(2,0.58); 
            pocketProbs["K7o"].Add(2,0.55); 
            pocketProbs["K6s"].Add(2,0.57); 
            pocketProbs["K6o"].Add(2,0.54); 
            pocketProbs["K5s"].Add(2,0.56); 
            pocketProbs["K5o"].Add(2,0.53); 
            pocketProbs["K4s"].Add(2,0.55); 
            pocketProbs["K4o"].Add(2,0.52); 
            pocketProbs["K3s"].Add(2,0.54); 
            pocketProbs["K3o"].Add(2,0.51); 
            pocketProbs["K2s"].Add(2,0.53); 
            pocketProbs["K2o"].Add(2,0.50); 
            pocketProbs["QQ"].Add(2,0.80); 
            pocketProbs["QJs"].Add(2,0.60); 
            pocketProbs["QJo"].Add(2,0.58); 
            pocketProbs["QTs"].Add(2,0.60); 
            pocketProbs["QTo"].Add(2,0.57); 
            pocketProbs["Q9s"].Add(2,0.58); 
            pocketProbs["Q9o"].Add(2,0.56); 
            pocketProbs["Q8s"].Add(2,0.56); 
            pocketProbs["Q8o"].Add(2,0.54); 
            pocketProbs["Q7s"].Add(2,0.55); 
            pocketProbs["Q7o"].Add(2,0.52); 
            pocketProbs["Q6s"].Add(2,0.54); 
            pocketProbs["Q6o"].Add(2,0.51); 
            pocketProbs["Q5s"].Add(2,0.53); 
            pocketProbs["Q5o"].Add(2,0.50); 
            pocketProbs["Q4s"].Add(2,0.52); 
            pocketProbs["Q4o"].Add(2,0.49); 
            pocketProbs["Q3s"].Add(2,0.51); 
            pocketProbs["Q3o"].Add(2,0.48); 
            pocketProbs["Q2s"].Add(2,0.50); 
            pocketProbs["Q2o"].Add(2,0.47); 
            pocketProbs["JJ"].Add(2,0.78); 
            pocketProbs["JTs"].Add(2,0.58); 
            pocketProbs["JTo"].Add(2,0.55); 
            pocketProbs["J9s"].Add(2,0.56); 
            pocketProbs["J9o"].Add(2,0.53); 
            pocketProbs["J8s"].Add(2,0.54); 
            pocketProbs["J8o"].Add(2,0.52); 
            pocketProbs["J7s"].Add(2,0.52); 
            pocketProbs["J7o"].Add(2,0.50); 
            pocketProbs["J6s"].Add(2,0.51); 
            pocketProbs["J6o"].Add(2,0.48); 
            pocketProbs["J5s"].Add(2,0.50); 
            pocketProbs["J5o"].Add(2,0.47); 
            pocketProbs["J4s"].Add(2,0.49); 
            pocketProbs["J4o"].Add(2,0.46); 
            pocketProbs["J3s"].Add(2,0.48); 
            pocketProbs["J3o"].Add(2,0.45); 
            pocketProbs["J2s"].Add(2,0.47); 
            pocketProbs["J2o"].Add(2,0.44); 
            pocketProbs["TT"].Add(2,0.75); 
            pocketProbs["T9s"].Add(2,0.54); 
            pocketProbs["T9o"].Add(2,0.52); 
            pocketProbs["T8s"].Add(2,0.53); 
            pocketProbs["T8o"].Add(2,0.50); 
            pocketProbs["T7s"].Add(2,0.51); 
            pocketProbs["T7o"].Add(2,0.48); 
            pocketProbs["T6s"].Add(2,0.49); 
            pocketProbs["T6o"].Add(2,0.46); 
            pocketProbs["T5s"].Add(2,0.47); 
            pocketProbs["T5o"].Add(2,0.44); 
            pocketProbs["T4s"].Add(2,0.46); 
            pocketProbs["T4o"].Add(2,0.43); 
            pocketProbs["T3s"].Add(2,0.46); 
            pocketProbs["T3o"].Add(2,0.42); 
            pocketProbs["T2s"].Add(2,0.45); 
            pocketProbs["T2o"].Add(2,0.42); 
            pocketProbs["99"].Add(2,0.72); 
            pocketProbs["98s"].Add(2,0.51); 
            pocketProbs["98o"].Add(2,0.48); 
            pocketProbs["97s"].Add(2,0.50); 
            pocketProbs["97o"].Add(2,0.47); 
            pocketProbs["96s"].Add(2,0.48); 
            pocketProbs["96o"].Add(2,0.45); 
            pocketProbs["95s"].Add(2,0.46); 
            pocketProbs["95o"].Add(2,0.43); 
            pocketProbs["94s"].Add(2,0.44); 
            pocketProbs["94o"].Add(2,0.41); 
            pocketProbs["93s"].Add(2,0.43); 
            pocketProbs["93o"].Add(2,0.40); 
            pocketProbs["92s"].Add(2,0.42); 
            pocketProbs["92o"].Add(2,0.39); 
            pocketProbs["88"].Add(2,0.69); 
            pocketProbs["87s"].Add(2,0.48); 
            pocketProbs["87o"].Add(2,0.46); 
            pocketProbs["86s"].Add(2,0.47); 
            pocketProbs["86o"].Add(2,0.44); 
            pocketProbs["85s"].Add(2,0.45); 
            pocketProbs["85o"].Add(2,0.42); 
            pocketProbs["84s"].Add(2,0.43); 
            pocketProbs["84o"].Add(2,0.40); 
            pocketProbs["83s"].Add(2,0.41); 
            pocketProbs["83o"].Add(2,0.38); 
            pocketProbs["82s"].Add(2,0.40); 
            pocketProbs["82o"].Add(2,0.37); 
            pocketProbs["77"].Add(2,0.66); 
            pocketProbs["76s"].Add(2,0.46); 
            pocketProbs["76o"].Add(2,0.43); 
            pocketProbs["75s"].Add(2,0.44); 
            pocketProbs["75o"].Add(2,0.41); 
            pocketProbs["74s"].Add(2,0.42); 
            pocketProbs["74o"].Add(2,0.39); 
            pocketProbs["73s"].Add(2,0.40); 
            pocketProbs["73o"].Add(2,0.37); 
            pocketProbs["72s"].Add(2,0.38); 
            pocketProbs["72o"].Add(2,0.35); 
            pocketProbs["66"].Add(2,0.63); 
            pocketProbs["65s"].Add(2,0.43); 
            pocketProbs["65o"].Add(2,0.40); 
            pocketProbs["64s"].Add(2,0.41); 
            pocketProbs["64o"].Add(2,0.38); 
            pocketProbs["63s"].Add(2,0.39); 
            pocketProbs["63o"].Add(2,0.36); 
            pocketProbs["62s"].Add(2,0.38); 
            pocketProbs["62o"].Add(2,0.34); 
            pocketProbs["55"].Add(2,0.60); 
            pocketProbs["54s"].Add(2,0.41); 
            pocketProbs["54o"].Add(2,0.38); 
            pocketProbs["53s"].Add(2,0.39); 
            pocketProbs["53o"].Add(2,0.36); 
            pocketProbs["52s"].Add(2,0.38); 
            pocketProbs["52o"].Add(2,0.34); 
            pocketProbs["44"].Add(2,0.57); 
            pocketProbs["43s"].Add(2,0.38); 
            pocketProbs["43o"].Add(2,0.34); 
            pocketProbs["42s"].Add(2,0.36); 
            pocketProbs["42o"].Add(2,0.33); 
            pocketProbs["33"].Add(2,0.54); 
            pocketProbs["32s"].Add(2,0.35); 
            pocketProbs["32o"].Add(2,0.31); 
            pocketProbs["22"].Add(2,0.50); 
            pocketProbs["AA"].Add(3,0.73); 
            pocketProbs["AKs"].Add(3,0.51); 
            pocketProbs["AKo"].Add(3,0.48); 
            pocketProbs["AQs"].Add(3,0.49); 
            pocketProbs["AQo"].Add(3,0.47); 
            pocketProbs["AJs"].Add(3,0.48); 
            pocketProbs["AJo"].Add(3,0.46); 
            pocketProbs["ATs"].Add(3,0.47); 
            pocketProbs["ATo"].Add(3,0.44); 
            pocketProbs["A9s"].Add(3,0.45); 
            pocketProbs["A9o"].Add(3,0.42); 
            pocketProbs["A8s"].Add(3,0.44); 
            pocketProbs["A8o"].Add(3,0.41); 
            pocketProbs["A7s"].Add(3,0.43); 
            pocketProbs["A7o"].Add(3,0.39); 
            pocketProbs["A6s"].Add(3,0.41); 
            pocketProbs["A6o"].Add(3,0.38); 
            pocketProbs["A5s"].Add(3,0.41); 
            pocketProbs["A5o"].Add(3,0.38); 
            pocketProbs["A4s"].Add(3,0.40); 
            pocketProbs["A4o"].Add(3,0.37); 
            pocketProbs["A3s"].Add(3,0.39); 
            pocketProbs["A3o"].Add(3,0.36); 
            pocketProbs["A2s"].Add(3,0.39); 
            pocketProbs["A2o"].Add(3,0.35); 
            pocketProbs["KK"].Add(3,0.69); 
            pocketProbs["KQs"].Add(3,0.47); 
            pocketProbs["KQo"].Add(3,0.44); 
            pocketProbs["KJs"].Add(3,0.46); 
            pocketProbs["KJo"].Add(3,0.43); 
            pocketProbs["KTs"].Add(3,0.45); 
            pocketProbs["KTo"].Add(3,0.42); 
            pocketProbs["K9s"].Add(3,0.42); 
            pocketProbs["K9o"].Add(3,0.40); 
            pocketProbs["K8s"].Add(3,0.40); 
            pocketProbs["K8o"].Add(3,0.37); 
            pocketProbs["K7s"].Add(3,0.39); 
            pocketProbs["K7o"].Add(3,0.36); 
            pocketProbs["K6s"].Add(3,0.38); 
            pocketProbs["K6o"].Add(3,0.35); 
            pocketProbs["K5s"].Add(3,0.37); 
            pocketProbs["K5o"].Add(3,0.34); 
            pocketProbs["K4s"].Add(3,0.36); 
            pocketProbs["K4o"].Add(3,0.33); 
            pocketProbs["K3s"].Add(3,0.36); 
            pocketProbs["K3o"].Add(3,0.32); 
            pocketProbs["K2s"].Add(3,0.35); 
            pocketProbs["K2o"].Add(3,0.31); 
            pocketProbs["QQ"].Add(3,0.65); 
            pocketProbs["QJs"].Add(3,0.44); 
            pocketProbs["QJo"].Add(3,0.41); 
            pocketProbs["QTs"].Add(3,0.43); 
            pocketProbs["QTo"].Add(3,0.40); 
            pocketProbs["Q9s"].Add(3,0.41); 
            pocketProbs["Q9o"].Add(3,0.38); 
            pocketProbs["Q8s"].Add(3,0.39); 
            pocketProbs["Q8o"].Add(3,0.35); 
            pocketProbs["Q7s"].Add(3,0.37); 
            pocketProbs["Q7o"].Add(3,0.33); 
            pocketProbs["Q6s"].Add(3,0.36); 
            pocketProbs["Q6o"].Add(3,0.32); 
            pocketProbs["Q5s"].Add(3,0.35); 
            pocketProbs["Q5o"].Add(3,0.31); 
            pocketProbs["Q4s"].Add(3,0.34); 
            pocketProbs["Q4o"].Add(3,0.30); 
            pocketProbs["Q3s"].Add(3,0.33); 
            pocketProbs["Q3o"].Add(3,0.29); 
            pocketProbs["Q2s"].Add(3,0.32); 
            pocketProbs["Q2o"].Add(3,0.28); 
            pocketProbs["JJ"].Add(3,0.61); 
            pocketProbs["JTs"].Add(3,0.42); 
            pocketProbs["JTo"].Add(3,0.39); 
            pocketProbs["J9s"].Add(3,0.40); 
            pocketProbs["J9o"].Add(3,0.37); 
            pocketProbs["J8s"].Add(3,0.38); 
            pocketProbs["J8o"].Add(3,0.34); 
            pocketProbs["J7s"].Add(3,0.35); 
            pocketProbs["J7o"].Add(3,0.32); 
            pocketProbs["J6s"].Add(3,0.34); 
            pocketProbs["J6o"].Add(3,0.30); 
            pocketProbs["J5s"].Add(3,0.33); 
            pocketProbs["J5o"].Add(3,0.29); 
            pocketProbs["J4s"].Add(3,0.32); 
            pocketProbs["J4o"].Add(3,0.28); 
            pocketProbs["J3s"].Add(3,0.31); 
            pocketProbs["J3o"].Add(3,0.27); 
            pocketProbs["J2s"].Add(3,0.30); 
            pocketProbs["J2o"].Add(3,0.26); 
            pocketProbs["TT"].Add(3,0.58); 
            pocketProbs["T9s"].Add(3,0.39); 
            pocketProbs["T9o"].Add(3,0.36); 
            pocketProbs["T8s"].Add(3,0.37); 
            pocketProbs["T8o"].Add(3,0.34); 
            pocketProbs["T7s"].Add(3,0.35); 
            pocketProbs["T7o"].Add(3,0.31); 
            pocketProbs["T6s"].Add(3,0.33); 
            pocketProbs["T6o"].Add(3,0.29); 
            pocketProbs["T5s"].Add(3,0.31); 
            pocketProbs["T5o"].Add(3,0.27); 
            pocketProbs["T4s"].Add(3,0.30); 
            pocketProbs["T4o"].Add(3,0.26); 
            pocketProbs["T3s"].Add(3,0.29); 
            pocketProbs["T3o"].Add(3,0.26); 
            pocketProbs["T2s"].Add(3,0.29); 
            pocketProbs["T2o"].Add(3,0.25); 
            pocketProbs["99"].Add(3,0.54); 
            pocketProbs["98s"].Add(3,0.36); 
            pocketProbs["98o"].Add(3,0.33); 
            pocketProbs["97s"].Add(3,0.34); 
            pocketProbs["97o"].Add(3,0.31); 
            pocketProbs["96s"].Add(3,0.32); 
            pocketProbs["96o"].Add(3,0.29); 
            pocketProbs["95s"].Add(3,0.30); 
            pocketProbs["95o"].Add(3,0.27); 
            pocketProbs["94s"].Add(3,0.28); 
            pocketProbs["94o"].Add(3,0.25); 
            pocketProbs["93s"].Add(3,0.28); 
            pocketProbs["93o"].Add(3,0.24); 
            pocketProbs["92s"].Add(3,0.27); 
            pocketProbs["92o"].Add(3,0.23); 
            pocketProbs["88"].Add(3,0.50); 
            pocketProbs["87s"].Add(3,0.34); 
            pocketProbs["87o"].Add(3,0.31); 
            pocketProbs["86s"].Add(3,0.32); 
            pocketProbs["86o"].Add(3,0.29); 
            pocketProbs["85s"].Add(3,0.30); 
            pocketProbs["85o"].Add(3,0.27); 
            pocketProbs["84s"].Add(3,0.28); 
            pocketProbs["84o"].Add(3,0.24); 
            pocketProbs["83s"].Add(3,0.26); 
            pocketProbs["83o"].Add(3,0.22); 
            pocketProbs["82s"].Add(3,0.26); 
            pocketProbs["82o"].Add(3,0.22); 
            pocketProbs["77"].Add(3,0.46); 
            pocketProbs["76s"].Add(3,0.32); 
            pocketProbs["76o"].Add(3,0.29); 
            pocketProbs["75s"].Add(3,0.30); 
            pocketProbs["75o"].Add(3,0.27); 
            pocketProbs["74s"].Add(3,0.28); 
            pocketProbs["74o"].Add(3,0.25); 
            pocketProbs["73s"].Add(3,0.26); 
            pocketProbs["73o"].Add(3,0.22); 
            pocketProbs["72s"].Add(3,0.25); 
            pocketProbs["72o"].Add(3,0.20); 
            pocketProbs["66"].Add(3,0.43); 
            pocketProbs["65s"].Add(3,0.30); 
            pocketProbs["65o"].Add(3,0.27); 
            pocketProbs["64s"].Add(3,0.29); 
            pocketProbs["64o"].Add(3,0.25); 
            pocketProbs["63s"].Add(3,0.27); 
            pocketProbs["63o"].Add(3,0.23); 
            pocketProbs["62s"].Add(3,0.25); 
            pocketProbs["62o"].Add(3,0.21); 
            pocketProbs["55"].Add(3,0.40); 
            pocketProbs["54s"].Add(3,0.29); 
            pocketProbs["54o"].Add(3,0.25); 
            pocketProbs["53s"].Add(3,0.27); 
            pocketProbs["53o"].Add(3,0.23); 
            pocketProbs["52s"].Add(3,0.25); 
            pocketProbs["52o"].Add(3,0.21); 
            pocketProbs["44"].Add(3,0.37); 
            pocketProbs["43s"].Add(3,0.26); 
            pocketProbs["43o"].Add(3,0.22); 
            pocketProbs["42s"].Add(3,0.25); 
            pocketProbs["42o"].Add(3,0.21); 
            pocketProbs["33"].Add(3,0.34); 
            pocketProbs["32s"].Add(3,0.24); 
            pocketProbs["32o"].Add(3,0.20); 
            pocketProbs["22"].Add(3,0.31); 
            pocketProbs["AA"].Add(4,0.64); 
            pocketProbs["AKs"].Add(4,0.41); 
            pocketProbs["AKo"].Add(4,0.39); 
            pocketProbs["AQs"].Add(4,0.40); 
            pocketProbs["AQo"].Add(4,0.37); 
            pocketProbs["AJs"].Add(4,0.39); 
            pocketProbs["AJo"].Add(4,0.35); 
            pocketProbs["ATs"].Add(4,0.37); 
            pocketProbs["ATo"].Add(4,0.34); 
            pocketProbs["A9s"].Add(4,0.35); 
            pocketProbs["A9o"].Add(4,0.31); 
            pocketProbs["A8s"].Add(4,0.34); 
            pocketProbs["A8o"].Add(4,0.30); 
            pocketProbs["A7s"].Add(4,0.33); 
            pocketProbs["A7o"].Add(4,0.29); 
            pocketProbs["A6s"].Add(4,0.31); 
            pocketProbs["A6o"].Add(4,0.28); 
            pocketProbs["A5s"].Add(4,0.32); 
            pocketProbs["A5o"].Add(4,0.28); 
            pocketProbs["A4s"].Add(4,0.31); 
            pocketProbs["A4o"].Add(4,0.27); 
            pocketProbs["A3s"].Add(4,0.30); 
            pocketProbs["A3o"].Add(4,0.26); 
            pocketProbs["A2s"].Add(4,0.29); 
            pocketProbs["A2o"].Add(4,0.25); 
            pocketProbs["KK"].Add(4,0.58); 
            pocketProbs["KQs"].Add(4,0.38); 
            pocketProbs["KQo"].Add(4,0.35); 
            pocketProbs["KJs"].Add(4,0.37); 
            pocketProbs["KJo"].Add(4,0.34); 
            pocketProbs["KTs"].Add(4,0.36); 
            pocketProbs["KTo"].Add(4,0.33); 
            pocketProbs["K9s"].Add(4,0.33); 
            pocketProbs["K9o"].Add(4,0.30); 
            pocketProbs["K8s"].Add(4,0.31); 
            pocketProbs["K8o"].Add(4,0.27); 
            pocketProbs["K7s"].Add(4,0.30); 
            pocketProbs["K7o"].Add(4,0.26); 
            pocketProbs["K6s"].Add(4,0.29); 
            pocketProbs["K6o"].Add(4,0.25); 
            pocketProbs["K5s"].Add(4,0.28); 
            pocketProbs["K5o"].Add(4,0.25); 
            pocketProbs["K4s"].Add(4,0.27); 
            pocketProbs["K4o"].Add(4,0.23); 
            pocketProbs["K3s"].Add(4,0.27); 
            pocketProbs["K3o"].Add(4,0.23); 
            pocketProbs["K2s"].Add(4,0.26); 
            pocketProbs["K2o"].Add(4,0.22); 
            pocketProbs["QQ"].Add(4,0.54); 
            pocketProbs["QJs"].Add(4,0.36); 
            pocketProbs["QJo"].Add(4,0.33); 
            pocketProbs["QTs"].Add(4,0.35); 
            pocketProbs["QTo"].Add(4,0.31); 
            pocketProbs["Q9s"].Add(4,0.32); 
            pocketProbs["Q9o"].Add(4,0.29); 
            pocketProbs["Q8s"].Add(4,0.30); 
            pocketProbs["Q8o"].Add(4,0.26); 
            pocketProbs["Q7s"].Add(4,0.28); 
            pocketProbs["Q7o"].Add(4,0.24); 
            pocketProbs["Q6s"].Add(4,0.27); 
            pocketProbs["Q6o"].Add(4,0.23); 
            pocketProbs["Q5s"].Add(4,0.26); 
            pocketProbs["Q5o"].Add(4,0.22); 
            pocketProbs["Q4s"].Add(4,0.26); 
            pocketProbs["Q4o"].Add(4,0.21); 
            pocketProbs["Q3s"].Add(4,0.25); 
            pocketProbs["Q3o"].Add(4,0.21); 
            pocketProbs["Q2s"].Add(4,0.24); 
            pocketProbs["Q2o"].Add(4,0.20); 
            pocketProbs["JJ"].Add(4,0.49); 
            pocketProbs["JTs"].Add(4,0.34); 
            pocketProbs["JTo"].Add(4,0.31); 
            pocketProbs["J9s"].Add(4,0.31); 
            pocketProbs["J9o"].Add(4,0.28); 
            pocketProbs["J8s"].Add(4,0.29); 
            pocketProbs["J8o"].Add(4,0.26); 
            pocketProbs["J7s"].Add(4,0.27); 
            pocketProbs["J7o"].Add(4,0.24); 
            pocketProbs["J6s"].Add(4,0.25); 
            pocketProbs["J6o"].Add(4,0.21); 
            pocketProbs["J5s"].Add(4,0.25); 
            pocketProbs["J5o"].Add(4,0.21); 
            pocketProbs["J4s"].Add(4,0.24); 
            pocketProbs["J4o"].Add(4,0.20); 
            pocketProbs["J3s"].Add(4,0.23); 
            pocketProbs["J3o"].Add(4,0.19); 
            pocketProbs["J2s"].Add(4,0.23); 
            pocketProbs["J2o"].Add(4,0.18); 
            pocketProbs["TT"].Add(4,0.45); 
            pocketProbs["T9s"].Add(4,0.31); 
            pocketProbs["T9o"].Add(4,0.28); 
            pocketProbs["T8s"].Add(4,0.29); 
            pocketProbs["T8o"].Add(4,0.25); 
            pocketProbs["T7s"].Add(4,0.27); 
            pocketProbs["T7o"].Add(4,0.23); 
            pocketProbs["T6s"].Add(4,0.25); 
            pocketProbs["T6o"].Add(4,0.21); 
            pocketProbs["T5s"].Add(4,0.23); 
            pocketProbs["T5o"].Add(4,0.19); 
            pocketProbs["T4s"].Add(4,0.23); 
            pocketProbs["T4o"].Add(4,0.19); 
            pocketProbs["T3s"].Add(4,0.22); 
            pocketProbs["T3o"].Add(4,0.18); 
            pocketProbs["T2s"].Add(4,0.21); 
            pocketProbs["T2o"].Add(4,0.17); 
            pocketProbs["99"].Add(4,0.41); 
            pocketProbs["98s"].Add(4,0.29); 
            pocketProbs["98o"].Add(4,0.25); 
            pocketProbs["97s"].Add(4,0.27); 
            pocketProbs["97o"].Add(4,0.23); 
            pocketProbs["96s"].Add(4,0.25); 
            pocketProbs["96o"].Add(4,0.21); 
            pocketProbs["95s"].Add(4,0.23); 
            pocketProbs["95o"].Add(4,0.19); 
            pocketProbs["94s"].Add(4,0.21); 
            pocketProbs["94o"].Add(4,0.17); 
            pocketProbs["93s"].Add(4,0.21); 
            pocketProbs["93o"].Add(4,0.17); 
            pocketProbs["92s"].Add(4,0.20); 
            pocketProbs["92o"].Add(4,0.16); 
            pocketProbs["88"].Add(4,0.38); 
            pocketProbs["87s"].Add(4,0.27); 
            pocketProbs["87o"].Add(4,0.23); 
            pocketProbs["86s"].Add(4,0.25); 
            pocketProbs["86o"].Add(4,0.21); 
            pocketProbs["85s"].Add(4,0.23); 
            pocketProbs["85o"].Add(4,0.19); 
            pocketProbs["84s"].Add(4,0.21); 
            pocketProbs["84o"].Add(4,0.18); 
            pocketProbs["83s"].Add(4,0.20); 
            pocketProbs["83o"].Add(4,0.16); 
            pocketProbs["82s"].Add(4,0.19); 
            pocketProbs["82o"].Add(4,0.15); 
            pocketProbs["77"].Add(4,0.34); 
            pocketProbs["76s"].Add(4,0.25); 
            pocketProbs["76o"].Add(4,0.22); 
            pocketProbs["75s"].Add(4,0.23); 
            pocketProbs["75o"].Add(4,0.20); 
            pocketProbs["74s"].Add(4,0.22); 
            pocketProbs["74o"].Add(4,0.18); 
            pocketProbs["73s"].Add(4,0.20); 
            pocketProbs["73o"].Add(4,0.16); 
            pocketProbs["72s"].Add(4,0.18); 
            pocketProbs["72o"].Add(4,0.14); 
            pocketProbs["66"].Add(4,0.32); 
            pocketProbs["65s"].Add(4,0.24); 
            pocketProbs["65o"].Add(4,0.20); 
            pocketProbs["64s"].Add(4,0.22); 
            pocketProbs["64o"].Add(4,0.18); 
            pocketProbs["63s"].Add(4,0.20); 
            pocketProbs["63o"].Add(4,0.16); 
            pocketProbs["62s"].Add(4,0.19); 
            pocketProbs["62o"].Add(4,0.15); 
            pocketProbs["55"].Add(4,0.29); 
            pocketProbs["54s"].Add(4,0.23); 
            pocketProbs["54o"].Add(4,0.19); 
            pocketProbs["53s"].Add(4,0.21); 
            pocketProbs["53o"].Add(4,0.17); 
            pocketProbs["52s"].Add(4,0.20); 
            pocketProbs["52o"].Add(4,0.15); 
            pocketProbs["44"].Add(4,0.26); 
            pocketProbs["43s"].Add(4,0.20); 
            pocketProbs["43o"].Add(4,0.16); 
            pocketProbs["42s"].Add(4,0.19); 
            pocketProbs["42o"].Add(4,0.15); 
            pocketProbs["33"].Add(4,0.24); 
            pocketProbs["32s"].Add(4,0.18); 
            pocketProbs["32o"].Add(4,0.14); 
            pocketProbs["22"].Add(4,0.22); 
            pocketProbs["AA"].Add(5,0.56); 
            pocketProbs["AKs"].Add(5,0.35); 
            pocketProbs["AKo"].Add(5,0.32); 
            pocketProbs["AQs"].Add(5,0.34); 
            pocketProbs["AQo"].Add(5,0.30); 
            pocketProbs["AJs"].Add(5,0.32); 
            pocketProbs["AJo"].Add(5,0.29); 
            pocketProbs["ATs"].Add(5,0.31); 
            pocketProbs["ATo"].Add(5,0.28); 
            pocketProbs["A9s"].Add(5,0.28); 
            pocketProbs["A9o"].Add(5,0.25); 
            pocketProbs["A8s"].Add(5,0.27); 
            pocketProbs["A8o"].Add(5,0.24); 
            pocketProbs["A7s"].Add(5,0.27); 
            pocketProbs["A7o"].Add(5,0.23); 
            pocketProbs["A6s"].Add(5,0.26); 
            pocketProbs["A6o"].Add(5,0.22); 
            pocketProbs["A5s"].Add(5,0.26); 
            pocketProbs["A5o"].Add(5,0.22); 
            pocketProbs["A4s"].Add(5,0.25); 
            pocketProbs["A4o"].Add(5,0.21); 
            pocketProbs["A3s"].Add(5,0.25); 
            pocketProbs["A3o"].Add(5,0.20); 
            pocketProbs["A2s"].Add(5,0.24); 
            pocketProbs["A2o"].Add(5,0.20); 
            pocketProbs["KK"].Add(5,0.50); 
            pocketProbs["KQs"].Add(5,0.33); 
            pocketProbs["KQo"].Add(5,0.29); 
            pocketProbs["KJs"].Add(5,0.31); 
            pocketProbs["KJo"].Add(5,0.28); 
            pocketProbs["KTs"].Add(5,0.30); 
            pocketProbs["KTo"].Add(5,0.27); 
            pocketProbs["K9s"].Add(5,0.27); 
            pocketProbs["K9o"].Add(5,0.24); 
            pocketProbs["K8s"].Add(5,0.25); 
            pocketProbs["K8o"].Add(5,0.21); 
            pocketProbs["K7s"].Add(5,0.25); 
            pocketProbs["K7o"].Add(5,0.21); 
            pocketProbs["K6s"].Add(5,0.24); 
            pocketProbs["K6o"].Add(5,0.20); 
            pocketProbs["K5s"].Add(5,0.23); 
            pocketProbs["K5o"].Add(5,0.19); 
            pocketProbs["K4s"].Add(5,0.22); 
            pocketProbs["K4o"].Add(5,0.18); 
            pocketProbs["K3s"].Add(5,0.22); 
            pocketProbs["K3o"].Add(5,0.18); 
            pocketProbs["K2s"].Add(5,0.21); 
            pocketProbs["K2o"].Add(5,0.17); 
            pocketProbs["QQ"].Add(5,0.45); 
            pocketProbs["QJs"].Add(5,0.30); 
            pocketProbs["QJo"].Add(5,0.27); 
            pocketProbs["QTs"].Add(5,0.29); 
            pocketProbs["QTo"].Add(5,0.26); 
            pocketProbs["Q9s"].Add(5,0.26); 
            pocketProbs["Q9o"].Add(5,0.23); 
            pocketProbs["Q8s"].Add(5,0.24); 
            pocketProbs["Q8o"].Add(5,0.21); 
            pocketProbs["Q7s"].Add(5,0.23); 
            pocketProbs["Q7o"].Add(5,0.19); 
            pocketProbs["Q6s"].Add(5,0.22); 
            pocketProbs["Q6o"].Add(5,0.18); 
            pocketProbs["Q5s"].Add(5,0.21); 
            pocketProbs["Q5o"].Add(5,0.17); 
            pocketProbs["Q4s"].Add(5,0.21); 
            pocketProbs["Q4o"].Add(5,0.16); 
            pocketProbs["Q3s"].Add(5,0.20); 
            pocketProbs["Q3o"].Add(5,0.16); 
            pocketProbs["Q2s"].Add(5,0.20); 
            pocketProbs["Q2o"].Add(5,0.15); 
            pocketProbs["JJ"].Add(5,0.40); 
            pocketProbs["JTs"].Add(5,0.29); 
            pocketProbs["JTo"].Add(5,0.25); 
            pocketProbs["J9s"].Add(5,0.26); 
            pocketProbs["J9o"].Add(5,0.23); 
            pocketProbs["J8s"].Add(5,0.24); 
            pocketProbs["J8o"].Add(5,0.20); 
            pocketProbs["J7s"].Add(5,0.22); 
            pocketProbs["J7o"].Add(5,0.18); 
            pocketProbs["J6s"].Add(5,0.21); 
            pocketProbs["J6o"].Add(5,0.17); 
            pocketProbs["J5s"].Add(5,0.20); 
            pocketProbs["J5o"].Add(5,0.16); 
            pocketProbs["J4s"].Add(5,0.19); 
            pocketProbs["J4o"].Add(5,0.15); 
            pocketProbs["J3s"].Add(5,0.19); 
            pocketProbs["J3o"].Add(5,0.15); 
            pocketProbs["J2s"].Add(5,0.18); 
            pocketProbs["J2o"].Add(5,0.14); 
            pocketProbs["TT"].Add(5,0.36); 
            pocketProbs["T9s"].Add(5,0.26); 
            pocketProbs["T9o"].Add(5,0.23); 
            pocketProbs["T8s"].Add(5,0.24); 
            pocketProbs["T8o"].Add(5,0.20); 
            pocketProbs["T7s"].Add(5,0.22); 
            pocketProbs["T7o"].Add(5,0.18); 
            pocketProbs["T6s"].Add(5,0.21); 
            pocketProbs["T6o"].Add(5,0.17); 
            pocketProbs["T5s"].Add(5,0.19); 
            pocketProbs["T5o"].Add(5,0.15); 
            pocketProbs["T4s"].Add(5,0.18); 
            pocketProbs["T4o"].Add(5,0.14); 
            pocketProbs["T3s"].Add(5,0.18); 
            pocketProbs["T3o"].Add(5,0.14); 
            pocketProbs["T2s"].Add(5,0.17); 
            pocketProbs["T2o"].Add(5,0.13); 
            pocketProbs["99"].Add(5,0.33); 
            pocketProbs["98s"].Add(5,0.24); 
            pocketProbs["98o"].Add(5,0.20); 
            pocketProbs["97s"].Add(5,0.22); 
            pocketProbs["97o"].Add(5,0.18); 
            pocketProbs["96s"].Add(5,0.20); 
            pocketProbs["96o"].Add(5,0.17); 
            pocketProbs["95s"].Add(5,0.19); 
            pocketProbs["95o"].Add(5,0.15); 
            pocketProbs["94s"].Add(5,0.17); 
            pocketProbs["94o"].Add(5,0.13); 
            pocketProbs["93s"].Add(5,0.17); 
            pocketProbs["93o"].Add(5,0.13); 
            pocketProbs["92s"].Add(5,0.16); 
            pocketProbs["92o"].Add(5,0.12); 
            pocketProbs["88"].Add(5,0.29); 
            pocketProbs["87s"].Add(5,0.22); 
            pocketProbs["87o"].Add(5,0.19); 
            pocketProbs["86s"].Add(5,0.21); 
            pocketProbs["86o"].Add(5,0.17); 
            pocketProbs["85s"].Add(5,0.19); 
            pocketProbs["85o"].Add(5,0.15); 
            pocketProbs["84s"].Add(5,0.17); 
            pocketProbs["84o"].Add(5,0.13); 
            pocketProbs["83s"].Add(5,0.16); 
            pocketProbs["83o"].Add(5,0.12); 
            pocketProbs["82s"].Add(5,0.16); 
            pocketProbs["82o"].Add(5,0.11); 
            pocketProbs["77"].Add(5,0.27); 
            pocketProbs["76s"].Add(5,0.21); 
            pocketProbs["76o"].Add(5,0.17); 
            pocketProbs["75s"].Add(5,0.19); 
            pocketProbs["75o"].Add(5,0.16); 
            pocketProbs["74s"].Add(5,0.18); 
            pocketProbs["74o"].Add(5,0.14); 
            pocketProbs["73s"].Add(5,0.16); 
            pocketProbs["73o"].Add(5,0.12); 
            pocketProbs["72s"].Add(5,0.15); 
            pocketProbs["72o"].Add(5,0.11); 
            pocketProbs["66"].Add(5,0.25); 
            pocketProbs["65s"].Add(5,0.20); 
            pocketProbs["65o"].Add(5,0.16); 
            pocketProbs["64s"].Add(5,0.18); 
            pocketProbs["64o"].Add(5,0.14); 
            pocketProbs["63s"].Add(5,0.17); 
            pocketProbs["63o"].Add(5,0.13); 
            pocketProbs["62s"].Add(5,0.15); 
            pocketProbs["62o"].Add(5,0.11); 
            pocketProbs["55"].Add(5,0.22); 
            pocketProbs["54s"].Add(5,0.19); 
            pocketProbs["54o"].Add(5,0.15); 
            pocketProbs["53s"].Add(5,0.18); 
            pocketProbs["53o"].Add(5,0.14); 
            pocketProbs["52s"].Add(5,0.16); 
            pocketProbs["52o"].Add(5,0.12); 
            pocketProbs["44"].Add(5,0.21); 
            pocketProbs["43s"].Add(5,0.17); 
            pocketProbs["43o"].Add(5,0.13); 
            pocketProbs["42s"].Add(5,0.16); 
            pocketProbs["42o"].Add(5,0.12); 
            pocketProbs["33"].Add(5,0.19); 
            pocketProbs["32s"].Add(5,0.15); 
            pocketProbs["32o"].Add(5,0.11); 
            pocketProbs["22"].Add(5,0.18); 
            pocketProbs["AA"].Add(6,0.49); 
            pocketProbs["AKs"].Add(6,0.31); 
            pocketProbs["AKo"].Add(6,0.28); 
            pocketProbs["AQs"].Add(6,0.29); 
            pocketProbs["AQo"].Add(6,0.26); 
            pocketProbs["AJs"].Add(6,0.28); 
            pocketProbs["AJo"].Add(6,0.24); 
            pocketProbs["ATs"].Add(6,0.27); 
            pocketProbs["ATo"].Add(6,0.23); 
            pocketProbs["A9s"].Add(6,0.24); 
            pocketProbs["A9o"].Add(6,0.20); 
            pocketProbs["A8s"].Add(6,0.23); 
            pocketProbs["A8o"].Add(6,0.19); 
            pocketProbs["A7s"].Add(6,0.23); 
            pocketProbs["A7o"].Add(6,0.18); 
            pocketProbs["A6s"].Add(6,0.22); 
            pocketProbs["A6o"].Add(6,0.18); 
            pocketProbs["A5s"].Add(6,0.22); 
            pocketProbs["A5o"].Add(6,0.18); 
            pocketProbs["A4s"].Add(6,0.22); 
            pocketProbs["A4o"].Add(6,0.17); 
            pocketProbs["A3s"].Add(6,0.21); 
            pocketProbs["A3o"].Add(6,0.17); 
            pocketProbs["A2s"].Add(6,0.20); 
            pocketProbs["A2o"].Add(6,0.16); 
            pocketProbs["KK"].Add(6,0.43); 
            pocketProbs["KQs"].Add(6,0.28); 
            pocketProbs["KQo"].Add(6,0.25); 
            pocketProbs["KJs"].Add(6,0.27); 
            pocketProbs["KJo"].Add(6,0.24); 
            pocketProbs["KTs"].Add(6,0.26); 
            pocketProbs["KTo"].Add(6,0.22); 
            pocketProbs["K9s"].Add(6,0.23); 
            pocketProbs["K9o"].Add(6,0.20); 
            pocketProbs["K8s"].Add(6,0.21); 
            pocketProbs["K8o"].Add(6,0.17); 
            pocketProbs["K7s"].Add(6,0.21); 
            pocketProbs["K7o"].Add(6,0.17); 
            pocketProbs["K6s"].Add(6,0.20); 
            pocketProbs["K6o"].Add(6,0.16); 
            pocketProbs["K5s"].Add(6,0.20); 
            pocketProbs["K5o"].Add(6,0.15); 
            pocketProbs["K4s"].Add(6,0.19); 
            pocketProbs["K4o"].Add(6,0.15); 
            pocketProbs["K3s"].Add(6,0.18); 
            pocketProbs["K3o"].Add(6,0.14); 
            pocketProbs["K2s"].Add(6,0.18); 
            pocketProbs["K2o"].Add(6,0.14); 
            pocketProbs["QQ"].Add(6,0.38); 
            pocketProbs["QJs"].Add(6,0.26); 
            pocketProbs["QJo"].Add(6,0.23); 
            pocketProbs["QTs"].Add(6,0.25); 
            pocketProbs["QTo"].Add(6,0.22); 
            pocketProbs["Q9s"].Add(6,0.23); 
            pocketProbs["Q9o"].Add(6,0.19); 
            pocketProbs["Q8s"].Add(6,0.21); 
            pocketProbs["Q8o"].Add(6,0.17); 
            pocketProbs["Q7s"].Add(6,0.19); 
            pocketProbs["Q7o"].Add(6,0.15); 
            pocketProbs["Q6s"].Add(6,0.19); 
            pocketProbs["Q6o"].Add(6,0.14); 
            pocketProbs["Q5s"].Add(6,0.18); 
            pocketProbs["Q5o"].Add(6,0.14); 
            pocketProbs["Q4s"].Add(6,0.18); 
            pocketProbs["Q4o"].Add(6,0.13); 
            pocketProbs["Q3s"].Add(6,0.17); 
            pocketProbs["Q3o"].Add(6,0.13); 
            pocketProbs["Q2s"].Add(6,0.17); 
            pocketProbs["Q2o"].Add(6,0.12); 
            pocketProbs["JJ"].Add(6,0.34); 
            pocketProbs["JTs"].Add(6,0.25); 
            pocketProbs["JTo"].Add(6,0.22); 
            pocketProbs["J9s"].Add(6,0.22); 
            pocketProbs["J9o"].Add(6,0.19); 
            pocketProbs["J8s"].Add(6,0.21); 
            pocketProbs["J8o"].Add(6,0.17); 
            pocketProbs["J7s"].Add(6,0.19); 
            pocketProbs["J7o"].Add(6,0.15); 
            pocketProbs["J6s"].Add(6,0.17); 
            pocketProbs["J6o"].Add(6,0.13); 
            pocketProbs["J5s"].Add(6,0.17); 
            pocketProbs["J5o"].Add(6,0.13); 
            pocketProbs["J4s"].Add(6,0.16); 
            pocketProbs["J4o"].Add(6,0.12); 
            pocketProbs["J3s"].Add(6,0.16); 
            pocketProbs["J3o"].Add(6,0.12); 
            pocketProbs["J2s"].Add(6,0.16); 
            pocketProbs["J2o"].Add(6,0.11); 
            pocketProbs["TT"].Add(6,0.30); 
            pocketProbs["T9s"].Add(6,0.23); 
            pocketProbs["T9o"].Add(6,0.19); 
            pocketProbs["T8s"].Add(6,0.21); 
            pocketProbs["T8o"].Add(6,0.17); 
            pocketProbs["T7s"].Add(6,0.19); 
            pocketProbs["T7o"].Add(6,0.15); 
            pocketProbs["T6s"].Add(6,0.17); 
            pocketProbs["T6o"].Add(6,0.13); 
            pocketProbs["T5s"].Add(6,0.16); 
            pocketProbs["T5o"].Add(6,0.12); 
            pocketProbs["T4s"].Add(6,0.16); 
            pocketProbs["T4o"].Add(6,0.12); 
            pocketProbs["T3s"].Add(6,0.15); 
            pocketProbs["T3o"].Add(6,0.11); 
            pocketProbs["T2s"].Add(6,0.15); 
            pocketProbs["T2o"].Add(6,0.11); 
            pocketProbs["99"].Add(6,0.27); 
            pocketProbs["98s"].Add(6,0.20); 
            pocketProbs["98o"].Add(6,0.17); 
            pocketProbs["97s"].Add(6,0.19); 
            pocketProbs["97o"].Add(6,0.15); 
            pocketProbs["96s"].Add(6,0.17); 
            pocketProbs["96o"].Add(6,0.14); 
            pocketProbs["95s"].Add(6,0.16); 
            pocketProbs["95o"].Add(6,0.12); 
            pocketProbs["94s"].Add(6,0.15); 
            pocketProbs["94o"].Add(6,0.11); 
            pocketProbs["93s"].Add(6,0.14); 
            pocketProbs["93o"].Add(6,0.10); 
            pocketProbs["92s"].Add(6,0.14); 
            pocketProbs["92o"].Add(6,0.10); 
            pocketProbs["88"].Add(6,0.24); 
            pocketProbs["87s"].Add(6,0.19); 
            pocketProbs["87o"].Add(6,0.15); 
            pocketProbs["86s"].Add(6,0.18); 
            pocketProbs["86o"].Add(6,0.14); 
            pocketProbs["85s"].Add(6,0.16); 
            pocketProbs["85o"].Add(6,0.12); 
            pocketProbs["84s"].Add(6,0.15); 
            pocketProbs["84o"].Add(6,0.11); 
            pocketProbs["83s"].Add(6,0.14); 
            pocketProbs["83o"].Add(6,0.10); 
            pocketProbs["82s"].Add(6,0.13); 
            pocketProbs["82o"].Add(6,0.09); 
            pocketProbs["77"].Add(6,0.22); 
            pocketProbs["76s"].Add(6,0.18); 
            pocketProbs["76o"].Add(6,0.14); 
            pocketProbs["75s"].Add(6,0.17); 
            pocketProbs["75o"].Add(6,0.13); 
            pocketProbs["74s"].Add(6,0.15); 
            pocketProbs["74o"].Add(6,0.11); 
            pocketProbs["73s"].Add(6,0.14); 
            pocketProbs["73o"].Add(6,0.10); 
            pocketProbs["72s"].Add(6,0.13); 
            pocketProbs["72o"].Add(6,0.09); 
            pocketProbs["66"].Add(6,0.20); 
            pocketProbs["65s"].Add(6,0.17); 
            pocketProbs["65o"].Add(6,0.13); 
            pocketProbs["64s"].Add(6,0.16); 
            pocketProbs["64o"].Add(6,0.12); 
            pocketProbs["63s"].Add(6,0.15); 
            pocketProbs["63o"].Add(6,0.11); 
            pocketProbs["62s"].Add(6,0.13); 
            pocketProbs["62o"].Add(6,0.09); 
            pocketProbs["55"].Add(6,0.19); 
            pocketProbs["54s"].Add(6,0.17); 
            pocketProbs["54o"].Add(6,0.13); 
            pocketProbs["53s"].Add(6,0.15); 
            pocketProbs["53o"].Add(6,0.11); 
            pocketProbs["52s"].Add(6,0.14); 
            pocketProbs["52o"].Add(6,0.10); 
            pocketProbs["44"].Add(6,0.17); 
            pocketProbs["43s"].Add(6,0.15); 
            pocketProbs["43o"].Add(6,0.11); 
            pocketProbs["42s"].Add(6,0.14); 
            pocketProbs["42o"].Add(6,0.10); 
            pocketProbs["33"].Add(6,0.16); 
            pocketProbs["32s"].Add(6,0.13); 
            pocketProbs["32o"].Add(6,0.09); 
            pocketProbs["22"].Add(6,0.16); 
            pocketProbs["AA"].Add(7,0.44); 
            pocketProbs["AKs"].Add(7,0.28); 
            pocketProbs["AKo"].Add(7,0.24); 
            pocketProbs["AQs"].Add(7,0.26); 
            pocketProbs["AQo"].Add(7,0.23); 
            pocketProbs["AJs"].Add(7,0.25); 
            pocketProbs["AJo"].Add(7,0.21); 
            pocketProbs["ATs"].Add(7,0.24); 
            pocketProbs["ATo"].Add(7,0.20); 
            pocketProbs["A9s"].Add(7,0.21); 
            pocketProbs["A9o"].Add(7,0.17); 
            pocketProbs["A8s"].Add(7,0.20); 
            pocketProbs["A8o"].Add(7,0.16); 
            pocketProbs["A7s"].Add(7,0.20); 
            pocketProbs["A7o"].Add(7,0.15); 
            pocketProbs["A6s"].Add(7,0.19); 
            pocketProbs["A6o"].Add(7,0.15); 
            pocketProbs["A5s"].Add(7,0.20); 
            pocketProbs["A5o"].Add(7,0.15); 
            pocketProbs["A4s"].Add(7,0.19); 
            pocketProbs["A4o"].Add(7,0.15); 
            pocketProbs["A3s"].Add(7,0.19); 
            pocketProbs["A3o"].Add(7,0.14); 
            pocketProbs["A2s"].Add(7,0.18); 
            pocketProbs["A2o"].Add(7,0.14); 
            pocketProbs["KK"].Add(7,0.38); 
            pocketProbs["KQs"].Add(7,0.25); 
            pocketProbs["KQo"].Add(7,0.22); 
            pocketProbs["KJs"].Add(7,0.24); 
            pocketProbs["KJo"].Add(7,0.20); 
            pocketProbs["KTs"].Add(7,0.23); 
            pocketProbs["KTo"].Add(7,0.19); 
            pocketProbs["K9s"].Add(7,0.20); 
            pocketProbs["K9o"].Add(7,0.17); 
            pocketProbs["K8s"].Add(7,0.19); 
            pocketProbs["K8o"].Add(7,0.15); 
            pocketProbs["K7s"].Add(7,0.18); 
            pocketProbs["K7o"].Add(7,0.14); 
            pocketProbs["K6s"].Add(7,0.18); 
            pocketProbs["K6o"].Add(7,0.13); 
            pocketProbs["K5s"].Add(7,0.17); 
            pocketProbs["K5o"].Add(7,0.13); 
            pocketProbs["K4s"].Add(7,0.17); 
            pocketProbs["K4o"].Add(7,0.12); 
            pocketProbs["K3s"].Add(7,0.16); 
            pocketProbs["K3o"].Add(7,0.12); 
            pocketProbs["K2s"].Add(7,0.16); 
            pocketProbs["K2o"].Add(7,0.12); 
            pocketProbs["QQ"].Add(7,0.33); 
            pocketProbs["QJs"].Add(7,0.23); 
            pocketProbs["QJo"].Add(7,0.20); 
            pocketProbs["QTs"].Add(7,0.22); 
            pocketProbs["QTo"].Add(7,0.19); 
            pocketProbs["Q9s"].Add(7,0.20); 
            pocketProbs["Q9o"].Add(7,0.16); 
            pocketProbs["Q8s"].Add(7,0.18); 
            pocketProbs["Q8o"].Add(7,0.14); 
            pocketProbs["Q7s"].Add(7,0.17); 
            pocketProbs["Q7o"].Add(7,0.13); 
            pocketProbs["Q6s"].Add(7,0.16); 
            pocketProbs["Q6o"].Add(7,0.12); 
            pocketProbs["Q5s"].Add(7,0.16); 
            pocketProbs["Q5o"].Add(7,0.12); 
            pocketProbs["Q4s"].Add(7,0.15); 
            pocketProbs["Q4o"].Add(7,0.11); 
            pocketProbs["Q3s"].Add(7,0.15); 
            pocketProbs["Q3o"].Add(7,0.11); 
            pocketProbs["Q2s"].Add(7,0.15); 
            pocketProbs["Q2o"].Add(7,0.10); 
            pocketProbs["JJ"].Add(7,0.29); 
            pocketProbs["JTs"].Add(7,0.22); 
            pocketProbs["JTo"].Add(7,0.19); 
            pocketProbs["J9s"].Add(7,0.20); 
            pocketProbs["J9o"].Add(7,0.16); 
            pocketProbs["J8s"].Add(7,0.18); 
            pocketProbs["J8o"].Add(7,0.14); 
            pocketProbs["J7s"].Add(7,0.16); 
            pocketProbs["J7o"].Add(7,0.12); 
            pocketProbs["J6s"].Add(7,0.15); 
            pocketProbs["J6o"].Add(7,0.11); 
            pocketProbs["J5s"].Add(7,0.15); 
            pocketProbs["J5o"].Add(7,0.11); 
            pocketProbs["J4s"].Add(7,0.14); 
            pocketProbs["J4o"].Add(7,0.10); 
            pocketProbs["J3s"].Add(7,0.14); 
            pocketProbs["J3o"].Add(7,0.10); 
            pocketProbs["J2s"].Add(7,0.14); 
            pocketProbs["J2o"].Add(7,0.09); 
            pocketProbs["TT"].Add(7,0.25); 
            pocketProbs["T9s"].Add(7,0.20); 
            pocketProbs["T9o"].Add(7,0.16); 
            pocketProbs["T8s"].Add(7,0.18); 
            pocketProbs["T8o"].Add(7,0.14); 
            pocketProbs["T7s"].Add(7,0.17); 
            pocketProbs["T7o"].Add(7,0.13); 
            pocketProbs["T6s"].Add(7,0.15); 
            pocketProbs["T6o"].Add(7,0.11); 
            pocketProbs["T5s"].Add(7,0.14); 
            pocketProbs["T5o"].Add(7,0.10); 
            pocketProbs["T4s"].Add(7,0.14); 
            pocketProbs["T4o"].Add(7,0.10); 
            pocketProbs["T3s"].Add(7,0.13); 
            pocketProbs["T3o"].Add(7,0.09); 
            pocketProbs["T2s"].Add(7,0.13); 
            pocketProbs["T2o"].Add(7,0.09); 
            pocketProbs["99"].Add(7,0.22); 
            pocketProbs["98s"].Add(7,0.18); 
            pocketProbs["98o"].Add(7,0.14); 
            pocketProbs["97s"].Add(7,0.17); 
            pocketProbs["97o"].Add(7,0.13); 
            pocketProbs["96s"].Add(7,0.15); 
            pocketProbs["96o"].Add(7,0.11); 
            pocketProbs["95s"].Add(7,0.14); 
            pocketProbs["95o"].Add(7,0.10); 
            pocketProbs["94s"].Add(7,0.13); 
            pocketProbs["94o"].Add(7,0.09); 
            pocketProbs["93s"].Add(7,0.13); 
            pocketProbs["93o"].Add(7,0.08); 
            pocketProbs["92s"].Add(7,0.12); 
            pocketProbs["92o"].Add(7,0.08); 
            pocketProbs["88"].Add(7,0.20); 
            pocketProbs["87s"].Add(7,0.17); 
            pocketProbs["87o"].Add(7,0.13); 
            pocketProbs["86s"].Add(7,0.16); 
            pocketProbs["86o"].Add(7,0.12); 
            pocketProbs["85s"].Add(7,0.14); 
            pocketProbs["85o"].Add(7,0.11); 
            pocketProbs["84s"].Add(7,0.13); 
            pocketProbs["84o"].Add(7,0.09); 
            pocketProbs["83s"].Add(7,0.12); 
            pocketProbs["83o"].Add(7,0.08); 
            pocketProbs["82s"].Add(7,0.12); 
            pocketProbs["82o"].Add(7,0.08); 
            pocketProbs["77"].Add(7,0.19); 
            pocketProbs["76s"].Add(7,0.16); 
            pocketProbs["76o"].Add(7,0.12); 
            pocketProbs["75s"].Add(7,0.15); 
            pocketProbs["75o"].Add(7,0.11); 
            pocketProbs["74s"].Add(7,0.14); 
            pocketProbs["74o"].Add(7,0.10); 
            pocketProbs["73s"].Add(7,0.12); 
            pocketProbs["73o"].Add(7,0.08); 
            pocketProbs["72s"].Add(7,0.11); 
            pocketProbs["72o"].Add(7,0.07); 
            pocketProbs["66"].Add(7,0.17); 
            pocketProbs["65s"].Add(7,0.15); 
            pocketProbs["65o"].Add(7,0.12); 
            pocketProbs["64s"].Add(7,0.14); 
            pocketProbs["64o"].Add(7,0.10); 
            pocketProbs["63s"].Add(7,0.13); 
            pocketProbs["63o"].Add(7,0.09); 
            pocketProbs["62s"].Add(7,0.12); 
            pocketProbs["62o"].Add(7,0.08); 
            pocketProbs["55"].Add(7,0.16); 
            pocketProbs["54s"].Add(7,0.15); 
            pocketProbs["54o"].Add(7,0.11); 
            pocketProbs["53s"].Add(7,0.14); 
            pocketProbs["53o"].Add(7,0.10); 
            pocketProbs["52s"].Add(7,0.13); 
            pocketProbs["52o"].Add(7,0.09); 
            pocketProbs["44"].Add(7,0.15); 
            pocketProbs["43s"].Add(7,0.13); 
            pocketProbs["43o"].Add(7,0.09); 
            pocketProbs["42s"].Add(7,0.12); 
            pocketProbs["42o"].Add(7,0.08); 
            pocketProbs["33"].Add(7,0.15); 
            pocketProbs["32s"].Add(7,0.12); 
            pocketProbs["32o"].Add(7,0.08); 
            pocketProbs["22"].Add(7,0.14); 
            pocketProbs["AA"].Add(8,0.39); 
            pocketProbs["AKs"].Add(8,0.25); 
            pocketProbs["AKo"].Add(8,0.22); 
            pocketProbs["AQs"].Add(8,0.23); 
            pocketProbs["AQo"].Add(8,0.20); 
            pocketProbs["AJs"].Add(8,0.22); 
            pocketProbs["AJo"].Add(8,0.18); 
            pocketProbs["ATs"].Add(8,0.21); 
            pocketProbs["ATo"].Add(8,0.17); 
            pocketProbs["A9s"].Add(8,0.19); 
            pocketProbs["A9o"].Add(8,0.15); 
            pocketProbs["A8s"].Add(8,0.18); 
            pocketProbs["A8o"].Add(8,0.14); 
            pocketProbs["A7s"].Add(8,0.17); 
            pocketProbs["A7o"].Add(8,0.13); 
            pocketProbs["A6s"].Add(8,0.17); 
            pocketProbs["A6o"].Add(8,0.13); 
            pocketProbs["A5s"].Add(8,0.18); 
            pocketProbs["A5o"].Add(8,0.13); 
            pocketProbs["A4s"].Add(8,0.17); 
            pocketProbs["A4o"].Add(8,0.13); 
            pocketProbs["A3s"].Add(8,0.17); 
            pocketProbs["A3o"].Add(8,0.12); 
            pocketProbs["A2s"].Add(8,0.16); 
            pocketProbs["A2o"].Add(8,0.12); 
            pocketProbs["KK"].Add(8,0.33); 
            pocketProbs["KQs"].Add(8,0.23); 
            pocketProbs["KQo"].Add(8,0.19); 
            pocketProbs["KJs"].Add(8,0.21); 
            pocketProbs["KJo"].Add(8,0.18); 
            pocketProbs["KTs"].Add(8,0.20); 
            pocketProbs["KTo"].Add(8,0.17); 
            pocketProbs["K9s"].Add(8,0.18); 
            pocketProbs["K9o"].Add(8,0.14); 
            pocketProbs["K8s"].Add(8,0.17); 
            pocketProbs["K8o"].Add(8,0.13); 
            pocketProbs["K7s"].Add(8,0.16); 
            pocketProbs["K7o"].Add(8,0.12); 
            pocketProbs["K6s"].Add(8,0.16); 
            pocketProbs["K6o"].Add(8,0.11); 
            pocketProbs["K5s"].Add(8,0.15); 
            pocketProbs["K5o"].Add(8,0.11); 
            pocketProbs["K4s"].Add(8,0.15); 
            pocketProbs["K4o"].Add(8,0.11); 
            pocketProbs["K3s"].Add(8,0.15); 
            pocketProbs["K3o"].Add(8,0.10); 
            pocketProbs["K2s"].Add(8,0.14); 
            pocketProbs["K2o"].Add(8,0.10); 
            pocketProbs["QQ"].Add(8,0.28); 
            pocketProbs["QJs"].Add(8,0.21); 
            pocketProbs["QJo"].Add(8,0.17); 
            pocketProbs["QTs"].Add(8,0.20); 
            pocketProbs["QTo"].Add(8,0.16); 
            pocketProbs["Q9s"].Add(8,0.18); 
            pocketProbs["Q9o"].Add(8,0.14); 
            pocketProbs["Q8s"].Add(8,0.16); 
            pocketProbs["Q8o"].Add(8,0.12); 
            pocketProbs["Q7s"].Add(8,0.15); 
            pocketProbs["Q7o"].Add(8,0.11); 
            pocketProbs["Q6s"].Add(8,0.14); 
            pocketProbs["Q6o"].Add(8,0.10); 
            pocketProbs["Q5s"].Add(8,0.14); 
            pocketProbs["Q5o"].Add(8,0.10); 
            pocketProbs["Q4s"].Add(8,0.14); 
            pocketProbs["Q4o"].Add(8,0.09); 
            pocketProbs["Q3s"].Add(8,0.13); 
            pocketProbs["Q3o"].Add(8,0.09); 
            pocketProbs["Q2s"].Add(8,0.13); 
            pocketProbs["Q2o"].Add(8,0.09); 
            pocketProbs["JJ"].Add(8,0.25); 
            pocketProbs["JTs"].Add(8,0.20); 
            pocketProbs["JTo"].Add(8,0.16); 
            pocketProbs["J9s"].Add(8,0.18); 
            pocketProbs["J9o"].Add(8,0.14); 
            pocketProbs["J8s"].Add(8,0.16); 
            pocketProbs["J8o"].Add(8,0.12); 
            pocketProbs["J7s"].Add(8,0.15); 
            pocketProbs["J7o"].Add(8,0.11); 
            pocketProbs["J6s"].Add(8,0.14); 
            pocketProbs["J6o"].Add(8,0.09); 
            pocketProbs["J5s"].Add(8,0.13); 
            pocketProbs["J5o"].Add(8,0.09); 
            pocketProbs["J4s"].Add(8,0.13); 
            pocketProbs["J4o"].Add(8,0.09); 
            pocketProbs["J3s"].Add(8,0.13); 
            pocketProbs["J3o"].Add(8,0.08); 
            pocketProbs["J2s"].Add(8,0.12); 
            pocketProbs["J2o"].Add(8,0.08); 
            pocketProbs["TT"].Add(8,0.22); 
            pocketProbs["T9s"].Add(8,0.18); 
            pocketProbs["T9o"].Add(8,0.14); 
            pocketProbs["T8s"].Add(8,0.16); 
            pocketProbs["T8o"].Add(8,0.13); 
            pocketProbs["T7s"].Add(8,0.15); 
            pocketProbs["T7o"].Add(8,0.11); 
            pocketProbs["T6s"].Add(8,0.14); 
            pocketProbs["T6o"].Add(8,0.10); 
            pocketProbs["T5s"].Add(8,0.12); 
            pocketProbs["T5o"].Add(8,0.08); 
            pocketProbs["T4s"].Add(8,0.12); 
            pocketProbs["T4o"].Add(8,0.08); 
            pocketProbs["T3s"].Add(8,0.12); 
            pocketProbs["T3o"].Add(8,0.08); 
            pocketProbs["T2s"].Add(8,0.12); 
            pocketProbs["T2o"].Add(8,0.08); 
            pocketProbs["99"].Add(8,0.19); 
            pocketProbs["98s"].Add(8,0.16); 
            pocketProbs["98o"].Add(8,0.12); 
            pocketProbs["97s"].Add(8,0.15); 
            pocketProbs["97o"].Add(8,0.11); 
            pocketProbs["96s"].Add(8,0.14); 
            pocketProbs["96o"].Add(8,0.10); 
            pocketProbs["95s"].Add(8,0.12); 
            pocketProbs["95o"].Add(8,0.09); 
            pocketProbs["94s"].Add(8,0.11); 
            pocketProbs["94o"].Add(8,0.07); 
            pocketProbs["93s"].Add(8,0.11); 
            pocketProbs["93o"].Add(8,0.07); 
            pocketProbs["92s"].Add(8,0.11); 
            pocketProbs["92o"].Add(8,0.07); 
            pocketProbs["88"].Add(8,0.18); 
            pocketProbs["87s"].Add(8,0.15); 
            pocketProbs["87o"].Add(8,0.12); 
            pocketProbs["86s"].Add(8,0.14); 
            pocketProbs["86o"].Add(8,0.10); 
            pocketProbs["85s"].Add(8,0.13); 
            pocketProbs["85o"].Add(8,0.09); 
            pocketProbs["84s"].Add(8,0.12); 
            pocketProbs["84o"].Add(8,0.08); 
            pocketProbs["83s"].Add(8,0.11); 
            pocketProbs["83o"].Add(8,0.07); 
            pocketProbs["82s"].Add(8,0.11); 
            pocketProbs["82o"].Add(8,0.06); 
            pocketProbs["77"].Add(8,0.16); 
            pocketProbs["76s"].Add(8,0.14); 
            pocketProbs["76o"].Add(8,0.11); 
            pocketProbs["75s"].Add(8,0.13); 
            pocketProbs["75o"].Add(8,0.10); 
            pocketProbs["74s"].Add(8,0.12); 
            pocketProbs["74o"].Add(8,0.09); 
            pocketProbs["73s"].Add(8,0.11); 
            pocketProbs["73o"].Add(8,0.07); 
            pocketProbs["72s"].Add(8,0.10); 
            pocketProbs["72o"].Add(8,0.06); 
            pocketProbs["66"].Add(8,0.15); 
            pocketProbs["65s"].Add(8,0.14); 
            pocketProbs["65o"].Add(8,0.10); 
            pocketProbs["64s"].Add(8,0.13); 
            pocketProbs["64o"].Add(8,0.09); 
            pocketProbs["63s"].Add(8,0.12); 
            pocketProbs["63o"].Add(8,0.08); 
            pocketProbs["62s"].Add(8,0.11); 
            pocketProbs["62o"].Add(8,0.07); 
            pocketProbs["55"].Add(8,0.14); 
            pocketProbs["54s"].Add(8,0.14); 
            pocketProbs["54o"].Add(8,0.10); 
            pocketProbs["53s"].Add(8,0.13); 
            pocketProbs["53o"].Add(8,0.09); 
            pocketProbs["52s"].Add(8,0.11); 
            pocketProbs["52o"].Add(8,0.08); 
            pocketProbs["44"].Add(8,0.14); 
            pocketProbs["43s"].Add(8,0.12); 
            pocketProbs["43o"].Add(8,0.08); 
            pocketProbs["42s"].Add(8,0.11); 
            pocketProbs["42o"].Add(8,0.07); 
            pocketProbs["33"].Add(8,0.14); 
            pocketProbs["32s"].Add(8,0.11); 
            pocketProbs["32o"].Add(8,0.07); 
            pocketProbs["22"].Add(8,0.13);
        }

        public override double EstProbWinningShowdown(GameState gameState)
        {
            string sRankDescription = gameState.MyCards.RankDescription();

            int numOpponents = gameState.NumActiveOpponents();

            double estimate = pocketProbs[sRankDescription][numOpponents + 1];

            return estimate;
        }
    }
}
